version: '3.2'

services:
  web:
    image: python-second-innings
    build:
      context: .
    network_mode: bridge
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  test:
    image: python-test-console
    build:
      context: .
      dockerfile: Dockerfile-test
    network_mode: bridge
    ports:
      - "3001:3001"
    volumes:
      - .:/code
  toss:
    image: python-toss
    build:
      context: .
    ports:
      - "3002:3002"
    volumes:
      - .:/code
  playgame:
    image: python-tie-breaker
    build:
      context: .
      dockerfile: Dockerfile-game
    ports:
      - "3003:3003"
    volumes:
      - .:/code
