version: '3.2'

services:
  web:
    image: python-console
    build:
      context: .
    network_mode: bridge
    ports:
      - "3000:3000"
    volumes:
      - .:/code
  test:
    image: python-test-console
    build:
      context: .
      dockerfile: Dockerfile-test
    network_mode: bridge
    ports:
      - "3001:3001"
    volumes:
      - .:/code
